# .coding-standards.yml
rules:
  # Bật/tắt quy tắc cụ thể
  C001:
    enabled: true
    level: error
  
  # Tùy chỉnh ngưỡng
  C002:
    enabled: true
    level: warning
    config:
      threshold: 120
      
# Bỏ qua các file/thư mục
exclude:
  - 'dist/**'
  - 'node_modules/**'
  - '**/*.test.js'
