name: Code Quality Check

on:
  push:
    branches: [ main, develop, master ]
  pull_request:
    branches: [ main, develop, master ]

jobs:
  coding-standards:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Run Coding Standards Check
        uses: chienpv-3590/coding-standards-action@v1
        with:
          rules: 'common,frontend'  # Các nhóm quy tắc cần kiểm tra
          fail-level: 'error'       # Mức độ lỗi để fail CI (error/warning)
          report-format: 'github'   # Format báo cáo (github/text/json)
